import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api } from '../utils/api';
import type { AppException, AuditEvent, Shipment } from '../types/models';

export default function ShipmentDetailPage() {
  const { id } = useParams(); const [tab, setTab] = useState('overview'); const [shipment, setShipment] = useState<Shipment | null>(null); const [exceptions, setExceptions] = useState<AppException[]>([]); const [audit, setAudit] = useState<AuditEvent[]>([]); const [bl, setBl] = useState<any>(null);
  const [revisionField, setRevisionField] = useState('consignee.address');
  const [correctedValue, setCorrectedValue] = useState('Prins Hendrikkade 150, Amsterdam 1011 AT, Netherlands');
  const [revisionReason, setRevisionReason] = useState('Shipper provided updated address');
  const [isGenerating, setIsGenerating] = useState(false);
  const load = async () => { const s = await api<Shipment>(`/api/shipments/${id}`); setShipment(s); setExceptions((await api<AppException[]>('/api/exceptions')).filter((e) => e.shipmentId === id)); setAudit(await api<AuditEvent[]>(`/api/audit/shipment/${id}`)); setBl(await api(`/api/shipments/${id}/bl`)); };
  useEffect(() => { load(); }, [id]);
  const allDocs = shipment ? Object.values(shipment.documentsReceived).every(Boolean) : false;
  const hasCriticalOpen = useMemo(() => exceptions.some((e) => e.status !== 'resolved' && e.severity === 'critical'), [exceptions]);
  if (!shipment) return <div>Loading...</div>;
  return <div><h2 className='text-xl font-semibold mb-3'>{shipment.referenceNumber}</h2>
    <div className='flex gap-2 mb-3'>{['overview','documents','exceptions','bl','audit'].map((t) => <button key={t} className={`px-3 py-1 rounded ${tab===t?'bg-primary text-white':'bg-white border'}`} onClick={() => setTab(t)}>{t.toUpperCase()}</button>)}</div>
    {tab === 'overview' && <div className='card grid grid-cols-2 gap-2 text-sm'><div><b>Shipping Line:</b> {shipment.shippingLine}</div><div><b>Booking Ref:</b> {shipment.bookingReferenceNumber}</div><div><b>Vessel:</b> {shipment.vesselName}</div><div><b>Voyage:</b> {shipment.voyageNumber}</div><div><b>Port Load:</b> {shipment.portOfLoading}</div><div><b>Port Discharge:</b> {shipment.portOfDischarge}</div><div><b>Shipper:</b> {shipment.shipperName}</div><div><b>Consignee:</b> {shipment.consigneeName}</div></div>}
    {tab === 'documents' && <div className='card'>Checklist: {Object.entries(shipment.documentsReceived).map(([k,v]) => <div key={k}>{v ? '✅' : '⏳'} {k}</div>)}</div>}
    {tab === 'exceptions' && <div className='card'>{exceptions.map((e) => <div key={e.id} className='border rounded p-2 mb-2'><div className='font-semibold'>{e.type} ({e.severity})</div><div>{e.description}</div></div>)}</div>}
    {tab === 'bl' && <div className='card space-y-3'>
      {!bl && <div>
        <div>Checklist: {allDocs ? '✅ all docs received' : '⚠ docs pending'} {hasCriticalOpen ? '⚠ critical exception open' : ''}</div>
        <button className='bg-primary text-white px-3 py-2 rounded mt-2' disabled={!allDocs || hasCriticalOpen || isGenerating} onClick={async() => { setIsGenerating(true); await new Promise((r) => setTimeout(r, 2000)); await api(`/api/shipments/${id}/generate-bl`, { method: 'POST' }); setIsGenerating(false); load(); }}>{isGenerating ? 'Generating...' : 'Generate BL Draft'}</button>
      </div>}
      {bl && <div>
        <div className='font-semibold'>BILL OF LADING DRAFT v{bl.version}</div>
        <div>Generated By: {bl.generatedBy}</div>
        <div>Generated At: {new Date(bl.generatedAt).toLocaleString()}</div>
        <div className='mt-2'>Shipper: {bl.shipper?.name}</div><div>Consignee: {bl.consignee?.name}</div><div>Port of Loading: {bl.portOfLoading}</div><div>Port of Discharge: {bl.portOfDischarge}</div><div>Cargo: {bl.cargoDescription}</div>
        <div className='grid grid-cols-4 gap-2 mt-3'>
          <select className='border rounded p-2' value={revisionField} onChange={(e) => setRevisionField(e.target.value)}>
            <option value='consignee.address'>Consignee Address</option>
            <option value='shipper.address'>Shipper Address</option>
            <option value='portOfDischarge'>Port of Discharge</option>
            <option value='cargoDescription'>Cargo Description</option>
          </select>
          <input className='col-span-2 border rounded p-2' value={correctedValue} onChange={(e) => setCorrectedValue(e.target.value)} />
          <input className='border rounded p-2' value={revisionReason} onChange={(e) => setRevisionReason(e.target.value)} />
        </div>
        <div className='flex gap-2 mt-2'>
          <button className='bg-primary text-white px-2 py-1 rounded' onClick={async()=>{await api(`/api/shipments/${id}/bl/approve`,{method:'POST',body:JSON.stringify({actor:'Priya Sharma'})});load();}}>Approve & Send to Shipper</button>
          <button className='border px-2 py-1 rounded' onClick={async()=>{await api(`/api/shipments/${id}/bl/revision`,{method:'POST',body:JSON.stringify({field:revisionField,correctedValue,reason:revisionReason,actor:'Priya Sharma'})});load();}}>Apply Revision</button>
        </div>
        {bl.revisions?.length > 0 && <div className='mt-3 text-sm'>{bl.revisions.map((r:any, i:number) => <div key={`${r.revisedAt}-${i}`} className='border-b py-1'>{r.field}: {r.previousValue} to {r.newValue} ({r.reason})</div>)}</div>}
      </div>}
    </div>}
    {tab === 'audit' && <div className='card'>{audit.map((a) => <div key={a.id} className='text-sm border-b py-1'>{new Date(a.timestamp).toLocaleString()} • {a.actor} • {a.description}</div>)}</div>}
  </div>;
}
